arm64:dts: Add I2C workarounds for PSUs SB1 Arthur
For the bring up, decrease the frequency to 100kHz as certain PSUs will
have flakey communication for busses 104, and 20X.

Also add the PSU FRUs to the DTS as to prevent I2C detect from causing
a bus hang. Devices that have drivers bound are skipped.
(IE `i2cdetect -y 200` would cause hang at address 0x52)

Tested:
Verified in Arthur RevA. AC cycled the units 3 times. Ensured each
time that the PSU FRU drivers were bound and `i2cdetect -y 200` didn't
cause a bus hang.

Note, performing a forced command will still hang the bus.
```
root@arthur:~# i2cget -y -f 200 0x52 0x00
Error: Read failed
root@arthur:~# i2cdetect -y 200
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00:                         ^C
```

Signed-off-by: Kyle Nieman <Kyle.Nieman@amd.com>