i2c: ast2700: Use bitbang for bus recovery
The register which is supposed to automate the CLK toggling isn't
functioning as there are no CLK pulses seen via oscilloscope when the
following debug logs are printed.
```
root@arthur:~# i2cget -y -f 104 0x52 0x00
Error: Read failed
root@arthur:~# dmesg -c
[  480.409399] i2c i2c-104: ioctl, cmd=0x705, arg=0xffffc939b0c8
[  480.409428] i2c i2c-104: ioctl, cmd=0x706, arg=0x52
[  480.409438] i2c i2c-104: ioctl, cmd=0x720, arg=0xffffc939b038
[  480.409458] i2c_ast2600 14c0fd00.i2c-bus: [0] write 1 byte to 0x70
[  480.409703] i2c_ast2600 14c0fd00.i2c-bus: bus12-m: 1 end
[  480.409714] i2c_ast2600 14c0fd00.i2c-bus: [0] write 1 byte to 0x52
[  480.409830] i2c_ast2600 14c0fd00.i2c-bus: bus12-m: -11 end
[  480.409841] i2c_ast2600 14c0fd00.i2c-bus: 12-bus recovery bus [a050000]
[  481.434535] i2c_ast2600 14c0fd00.i2c-bus: recovery timed out
```

Instead, toggle SCL and SDA manually via a different register in order
to repeat a stop condition 9 times like the I2C core driver.

This method is enabled per I2C controller via
`aspeed,bitbang-bus-recovery` DTS property.

Tested:
Verified in Arthur RevA that the a command to I2C Bus 200 address 0x52
hangs and recovers.
```
root@arthur:~# i2cget -y -f 200 0x52 0x00
Error: Read failed
root@arthur:~# dmesg -c
[ 2192.969838] i2c i2c-200: ioctl, cmd=0x705, arg=0xffffd66f0758
[ 2192.969867] i2c i2c-200: ioctl, cmd=0x706, arg=0x52
[ 2192.969877] i2c i2c-200: ioctl, cmd=0x720, arg=0xffffd66f06c8
[ 2192.969897] i2c_ast2600 14c0fd00.i2c-bus: [0] write 1 byte to 0x70
[ 2192.970137] i2c_ast2600 14c0fd00.i2c-bus: bus12-m: 1 end
[ 2192.970149] i2c_ast2600 14c0fd00.i2c-bus: [0] write 1 byte to 0x75
[ 2192.970370] i2c_ast2600 14c0fd00.i2c-bus: bus12-m: 1 end
[ 2192.970380] i2c_ast2600 14c0fd00.i2c-bus: [0] write 1 byte to 0x70
[ 2192.970600] i2c_ast2600 14c0fd00.i2c-bus: bus12-m: 1 end
[ 2192.970611] i2c_ast2600 14c0fd00.i2c-bus: [0] write 1 byte to 0x70
[ 2192.970831] i2c_ast2600 14c0fd00.i2c-bus: bus12-m: 1 end
[ 2192.970841] i2c_ast2600 14c0fd00.i2c-bus: [0] write 1 byte to 0x52
[ 2192.971046] i2c_ast2600 14c0fd00.i2c-bus: [1] read 1 byte from 0x52
[ 2192.971169] i2c_ast2600 14c0fd00.i2c-bus: bus12-m: -11 end
[ 2192.971180] i2c_ast2600 14c0fd00.i2c-bus: 12-bus recovery bus [a050000]
[ 2192.971353] i2c_ast2600 14c0fd00.i2c-bus: [0] write 1 byte to 0x70
[ 2192.971574] i2c_ast2600 14c0fd00.i2c-bus: bus12-m: 1 end
[ 2192.971584] i2c_ast2600 14c0fd00.i2c-bus: [0] write 1 byte to 0x70
[ 2192.971805] i2c_ast2600 14c0fd00.i2c-bus: bus12-m: 1 end
[ 2192.971814] i2c_ast2600 14c0fd00.i2c-bus: [0] write 1 byte to 0x75
[ 2192.972034] i2c_ast2600 14c0fd00.i2c-bus: bus12-m: 1 end
[ 2192.972044] i2c_ast2600 14c0fd00.i2c-bus: [0] write 1 byte to 0x70
[ 2192.972265] i2c_ast2600 14c0fd00.i2c-bus: bus12-m: 1 end
```